# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: produce_url_resp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='produce_url_resp.proto',
  package='spider',
  serialized_pb='\n\x16produce_url_resp.proto\x12\x06spider\"\x1f\n\x10produce_url_resp\x12\x0b\n\x03res\x18\x01 \x02(\x05')




_PRODUCE_URL_RESP = _descriptor.Descriptor(
  name='produce_url_resp',
  full_name='spider.produce_url_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='spider.produce_url_resp.res', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['produce_url_resp'] = _PRODUCE_URL_RESP

class produce_url_resp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRODUCE_URL_RESP

  # @@protoc_insertion_point(class_scope:spider.produce_url_resp)


# @@protoc_insertion_point(module_scope)
