# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: producer_register_resp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='producer_register_resp.proto',
  package='spider',
  serialized_pb='\n\x1cproducer_register_resp.proto\x12\x06spider\"1\n\x16producer_register_resp\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0b\n\x03res\x18\x02 \x02(\x05')




_PRODUCER_REGISTER_RESP = _descriptor.Descriptor(
  name='producer_register_resp',
  full_name='spider.producer_register_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='spider.producer_register_resp.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='spider.producer_register_resp.res', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['producer_register_resp'] = _PRODUCER_REGISTER_RESP

class producer_register_resp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRODUCER_REGISTER_RESP

  # @@protoc_insertion_point(class_scope:spider.producer_register_resp)


# @@protoc_insertion_point(module_scope)
