# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: produce_url_resp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='produce_url_resp.proto',
  package='spider',
  syntax='proto2',
  serialized_pb=_b('\n\x16produce_url_resp.proto\x12\x06spider\"\x1f\n\x10produce_url_resp\x12\x0b\n\x03res\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PRODUCE_URL_RESP = _descriptor.Descriptor(
  name='produce_url_resp',
  full_name='spider.produce_url_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='spider.produce_url_resp.res', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['produce_url_resp'] = _PRODUCE_URL_RESP

produce_url_resp = _reflection.GeneratedProtocolMessageType('produce_url_resp', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCE_URL_RESP,
  __module__ = 'produce_url_resp_pb2'
  # @@protoc_insertion_point(class_scope:spider.produce_url_resp)
  ))
_sym_db.RegisterMessage(produce_url_resp)


# @@protoc_insertion_point(module_scope)
