# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer_capacity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consumer_capacity.proto',
  package='spider',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x63onsumer_capacity.proto\x12\x06spider\"$\n\x15\x63onsumer_capacity_req\x12\x0b\n\x03\x63\x61p\x18\x01 \x02(\x05\"%\n\x16\x63onsumer_capacity_resp\x12\x0b\n\x03res\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONSUMER_CAPACITY_REQ = _descriptor.Descriptor(
  name='consumer_capacity_req',
  full_name='spider.consumer_capacity_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cap', full_name='spider.consumer_capacity_req.cap', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=71,
)


_CONSUMER_CAPACITY_RESP = _descriptor.Descriptor(
  name='consumer_capacity_resp',
  full_name='spider.consumer_capacity_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='spider.consumer_capacity_resp.res', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['consumer_capacity_req'] = _CONSUMER_CAPACITY_REQ
DESCRIPTOR.message_types_by_name['consumer_capacity_resp'] = _CONSUMER_CAPACITY_RESP

consumer_capacity_req = _reflection.GeneratedProtocolMessageType('consumer_capacity_req', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMER_CAPACITY_REQ,
  __module__ = 'consumer_capacity_pb2'
  # @@protoc_insertion_point(class_scope:spider.consumer_capacity_req)
  ))
_sym_db.RegisterMessage(consumer_capacity_req)

consumer_capacity_resp = _reflection.GeneratedProtocolMessageType('consumer_capacity_resp', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMER_CAPACITY_RESP,
  __module__ = 'consumer_capacity_pb2'
  # @@protoc_insertion_point(class_scope:spider.consumer_capacity_resp)
  ))
_sym_db.RegisterMessage(consumer_capacity_resp)


# @@protoc_insertion_point(module_scope)
