# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consume_url_resp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consume_url_resp.proto',
  package='spider',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x63onsume_url_resp.proto\x12\x06spider\"J\n\x10\x63onsume_url_resp\x12\x0b\n\x03res\x18\x01 \x02(\x05\x12\x13\n\x0b\x66\x61iled_urls\x18\x02 \x03(\t\x12\x14\n\x0csuccess_urls\x18\x03 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONSUME_URL_RESP = _descriptor.Descriptor(
  name='consume_url_resp',
  full_name='spider.consume_url_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='spider.consume_url_resp.res', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failed_urls', full_name='spider.consume_url_resp.failed_urls', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success_urls', full_name='spider.consume_url_resp.success_urls', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['consume_url_resp'] = _CONSUME_URL_RESP

consume_url_resp = _reflection.GeneratedProtocolMessageType('consume_url_resp', (_message.Message,), dict(
  DESCRIPTOR = _CONSUME_URL_RESP,
  __module__ = 'consume_url_resp_pb2'
  # @@protoc_insertion_point(class_scope:spider.consume_url_resp)
  ))
_sym_db.RegisterMessage(consume_url_resp)


# @@protoc_insertion_point(module_scope)
