# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consume_url_req.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consume_url_req.proto',
  package='spider',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x63onsume_url_req.proto\x12\x06spider\"\x1f\n\x0f\x63onsume_url_req\x12\x0c\n\x04urls\x18\x01 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONSUME_URL_REQ = _descriptor.Descriptor(
  name='consume_url_req',
  full_name='spider.consume_url_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='urls', full_name='spider.consume_url_req.urls', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['consume_url_req'] = _CONSUME_URL_REQ

consume_url_req = _reflection.GeneratedProtocolMessageType('consume_url_req', (_message.Message,), dict(
  DESCRIPTOR = _CONSUME_URL_REQ,
  __module__ = 'consume_url_req_pb2'
  # @@protoc_insertion_point(class_scope:spider.consume_url_req)
  ))
_sym_db.RegisterMessage(consume_url_req)


# @@protoc_insertion_point(module_scope)
