# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong_resp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pingpong_resp.proto',
  package='spider',
  serialized_pb='\n\x13pingpong_resp.proto\x12\x06spider\"\x1c\n\rpingpong_resp\x12\x0b\n\x03num\x18\x01 \x02(\x05')




_PINGPONG_RESP = _descriptor.Descriptor(
  name='pingpong_resp',
  full_name='spider.pingpong_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='spider.pingpong_resp.num', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['pingpong_resp'] = _PINGPONG_RESP

class pingpong_resp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PINGPONG_RESP

  # @@protoc_insertion_point(class_scope:spider.pingpong_resp)


# @@protoc_insertion_point(module_scope)
