# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong_req.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pingpong_req.proto',
  package='spider',
  syntax='proto2',
  serialized_pb=_b('\n\x12pingpong_req.proto\x12\x06spider\"\x1b\n\x0cpingpong_req\x12\x0b\n\x03num\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PINGPONG_REQ = _descriptor.Descriptor(
  name='pingpong_req',
  full_name='spider.pingpong_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='spider.pingpong_req.num', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['pingpong_req'] = _PINGPONG_REQ

pingpong_req = _reflection.GeneratedProtocolMessageType('pingpong_req', (_message.Message,), dict(
  DESCRIPTOR = _PINGPONG_REQ,
  __module__ = 'pingpong_req_pb2'
  # @@protoc_insertion_point(class_scope:spider.pingpong_req)
  ))
_sym_db.RegisterMessage(pingpong_req)


# @@protoc_insertion_point(module_scope)
