# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubscribeReq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SubscribeReq.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12SubscribeReq.proto\"X\n\x0cSubscribeReq\x12\x10\n\x08subReqID\x18\x01 \x02(\x05\x12\x10\n\x08userName\x18\x02 \x02(\t\x12\x13\n\x0bproductName\x18\x03 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x02(\tB\x1d\n\x08\x63om.wongB\x11SubscribeReqProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SUBSCRIBEREQ = _descriptor.Descriptor(
  name='SubscribeReq',
  full_name='SubscribeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subReqID', full_name='SubscribeReq.subReqID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userName', full_name='SubscribeReq.userName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productName', full_name='SubscribeReq.productName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='SubscribeReq.address', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['SubscribeReq'] = _SUBSCRIBEREQ

SubscribeReq = _reflection.GeneratedProtocolMessageType('SubscribeReq', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEREQ,
  __module__ = 'SubscribeReq_pb2'
  # @@protoc_insertion_point(class_scope:SubscribeReq)
  ))
_sym_db.RegisterMessage(SubscribeReq)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\010com.wongB\021SubscribeReqProto'))
# @@protoc_insertion_point(module_scope)
