// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consume_url_req.proto

#ifndef PROTOBUF_consume_5furl_5freq_2eproto__INCLUDED
#define PROTOBUF_consume_5furl_5freq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace spider {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_consume_5furl_5freq_2eproto();
void protobuf_AssignDesc_consume_5furl_5freq_2eproto();
void protobuf_ShutdownFile_consume_5furl_5freq_2eproto();

class consume_url_req;

// ===================================================================

class consume_url_req : public ::google::protobuf::Message {
 public:
  consume_url_req();
  virtual ~consume_url_req();

  consume_url_req(const consume_url_req& from);

  inline consume_url_req& operator=(const consume_url_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const consume_url_req& default_instance();

  void Swap(consume_url_req* other);

  // implements Message ----------------------------------------------

  inline consume_url_req* New() const { return New(NULL); }

  consume_url_req* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const consume_url_req& from);
  void MergeFrom(const consume_url_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(consume_url_req* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string urls = 1;
  int urls_size() const;
  void clear_urls();
  static const int kUrlsFieldNumber = 1;
  const ::std::string& urls(int index) const;
  ::std::string* mutable_urls(int index);
  void set_urls(int index, const ::std::string& value);
  void set_urls(int index, const char* value);
  void set_urls(int index, const char* value, size_t size);
  ::std::string* add_urls();
  void add_urls(const ::std::string& value);
  void add_urls(const char* value);
  void add_urls(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& urls() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_urls();

  // @@protoc_insertion_point(class_scope:spider.consume_url_req)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> urls_;
  friend void  protobuf_AddDesc_consume_5furl_5freq_2eproto();
  friend void protobuf_AssignDesc_consume_5furl_5freq_2eproto();
  friend void protobuf_ShutdownFile_consume_5furl_5freq_2eproto();

  void InitAsDefaultInstance();
  static consume_url_req* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// consume_url_req

// repeated string urls = 1;
inline int consume_url_req::urls_size() const {
  return urls_.size();
}
inline void consume_url_req::clear_urls() {
  urls_.Clear();
}
inline const ::std::string& consume_url_req::urls(int index) const {
  // @@protoc_insertion_point(field_get:spider.consume_url_req.urls)
  return urls_.Get(index);
}
inline ::std::string* consume_url_req::mutable_urls(int index) {
  // @@protoc_insertion_point(field_mutable:spider.consume_url_req.urls)
  return urls_.Mutable(index);
}
inline void consume_url_req::set_urls(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:spider.consume_url_req.urls)
  urls_.Mutable(index)->assign(value);
}
inline void consume_url_req::set_urls(int index, const char* value) {
  urls_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:spider.consume_url_req.urls)
}
inline void consume_url_req::set_urls(int index, const char* value, size_t size) {
  urls_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:spider.consume_url_req.urls)
}
inline ::std::string* consume_url_req::add_urls() {
  return urls_.Add();
}
inline void consume_url_req::add_urls(const ::std::string& value) {
  urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:spider.consume_url_req.urls)
}
inline void consume_url_req::add_urls(const char* value) {
  urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:spider.consume_url_req.urls)
}
inline void consume_url_req::add_urls(const char* value, size_t size) {
  urls_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:spider.consume_url_req.urls)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
consume_url_req::urls() const {
  // @@protoc_insertion_point(field_list:spider.consume_url_req.urls)
  return urls_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
consume_url_req::mutable_urls() {
  // @@protoc_insertion_point(field_mutable_list:spider.consume_url_req.urls)
  return &urls_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace spider

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_consume_5furl_5freq_2eproto__INCLUDED
