// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consume_url_resp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "consume_url_resp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace spider {

namespace {

const ::google::protobuf::Descriptor* consume_url_resp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  consume_url_resp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_consume_5furl_5fresp_2eproto() {
  protobuf_AddDesc_consume_5furl_5fresp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "consume_url_resp.proto");
  GOOGLE_CHECK(file != NULL);
  consume_url_resp_descriptor_ = file->message_type(0);
  static const int consume_url_resp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(consume_url_resp, res_),
  };
  consume_url_resp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      consume_url_resp_descriptor_,
      consume_url_resp::default_instance_,
      consume_url_resp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(consume_url_resp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(consume_url_resp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(consume_url_resp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_consume_5furl_5fresp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    consume_url_resp_descriptor_, &consume_url_resp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_consume_5furl_5fresp_2eproto() {
  delete consume_url_resp::default_instance_;
  delete consume_url_resp_reflection_;
}

void protobuf_AddDesc_consume_5furl_5fresp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026consume_url_resp.proto\022\006spider\"\037\n\020cons"
    "ume_url_resp\022\013\n\003res\030\001 \002(\005", 65);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "consume_url_resp.proto", &protobuf_RegisterTypes);
  consume_url_resp::default_instance_ = new consume_url_resp();
  consume_url_resp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_consume_5furl_5fresp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_consume_5furl_5fresp_2eproto {
  StaticDescriptorInitializer_consume_5furl_5fresp_2eproto() {
    protobuf_AddDesc_consume_5furl_5fresp_2eproto();
  }
} static_descriptor_initializer_consume_5furl_5fresp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int consume_url_resp::kResFieldNumber;
#endif  // !_MSC_VER

consume_url_resp::consume_url_resp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void consume_url_resp::InitAsDefaultInstance() {
}

consume_url_resp::consume_url_resp(const consume_url_resp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void consume_url_resp::SharedCtor() {
  _cached_size_ = 0;
  res_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

consume_url_resp::~consume_url_resp() {
  SharedDtor();
}

void consume_url_resp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void consume_url_resp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* consume_url_resp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return consume_url_resp_descriptor_;
}

const consume_url_resp& consume_url_resp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_consume_5furl_5fresp_2eproto();
  return *default_instance_;
}

consume_url_resp* consume_url_resp::default_instance_ = NULL;

consume_url_resp* consume_url_resp::New() const {
  return new consume_url_resp;
}

void consume_url_resp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    res_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool consume_url_resp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 res = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &res_)));
          set_has_res();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void consume_url_resp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 res = 1;
  if (has_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->res(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* consume_url_resp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 res = 1;
  if (has_res()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->res(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int consume_url_resp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 res = 1;
    if (has_res()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->res());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void consume_url_resp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const consume_url_resp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const consume_url_resp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void consume_url_resp::MergeFrom(const consume_url_resp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_res()) {
      set_res(from.res());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void consume_url_resp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void consume_url_resp::CopyFrom(const consume_url_resp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool consume_url_resp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void consume_url_resp::Swap(consume_url_resp* other) {
  if (other != this) {
    std::swap(res_, other->res_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata consume_url_resp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = consume_url_resp_descriptor_;
  metadata.reflection = consume_url_resp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace spider

// @@protoc_insertion_point(global_scope)
