// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consume_url_resp.proto

#ifndef PROTOBUF_consume_5furl_5fresp_2eproto__INCLUDED
#define PROTOBUF_consume_5furl_5fresp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace spider {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_consume_5furl_5fresp_2eproto();
void protobuf_AssignDesc_consume_5furl_5fresp_2eproto();
void protobuf_ShutdownFile_consume_5furl_5fresp_2eproto();

class consume_url_resp;

// ===================================================================

class consume_url_resp : public ::google::protobuf::Message {
 public:
  consume_url_resp();
  virtual ~consume_url_resp();

  consume_url_resp(const consume_url_resp& from);

  inline consume_url_resp& operator=(const consume_url_resp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const consume_url_resp& default_instance();

  void Swap(consume_url_resp* other);

  // implements Message ----------------------------------------------

  consume_url_resp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const consume_url_resp& from);
  void MergeFrom(const consume_url_resp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 res = 1;
  inline bool has_res() const;
  inline void clear_res();
  static const int kResFieldNumber = 1;
  inline ::google::protobuf::int32 res() const;
  inline void set_res(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:spider.consume_url_resp)
 private:
  inline void set_has_res();
  inline void clear_has_res();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 res_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_consume_5furl_5fresp_2eproto();
  friend void protobuf_AssignDesc_consume_5furl_5fresp_2eproto();
  friend void protobuf_ShutdownFile_consume_5furl_5fresp_2eproto();

  void InitAsDefaultInstance();
  static consume_url_resp* default_instance_;
};
// ===================================================================


// ===================================================================

// consume_url_resp

// required int32 res = 1;
inline bool consume_url_resp::has_res() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void consume_url_resp::set_has_res() {
  _has_bits_[0] |= 0x00000001u;
}
inline void consume_url_resp::clear_has_res() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void consume_url_resp::clear_res() {
  res_ = 0;
  clear_has_res();
}
inline ::google::protobuf::int32 consume_url_resp::res() const {
  return res_;
}
inline void consume_url_resp::set_res(::google::protobuf::int32 value) {
  set_has_res();
  res_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace spider

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_consume_5furl_5fresp_2eproto__INCLUDED
