// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consume_url_req.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "consume_url_req.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace spider {

namespace {

const ::google::protobuf::Descriptor* consume_url_req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  consume_url_req_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_consume_5furl_5freq_2eproto() {
  protobuf_AddDesc_consume_5furl_5freq_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "consume_url_req.proto");
  GOOGLE_CHECK(file != NULL);
  consume_url_req_descriptor_ = file->message_type(0);
  static const int consume_url_req_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(consume_url_req, urls_),
  };
  consume_url_req_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      consume_url_req_descriptor_,
      consume_url_req::default_instance_,
      consume_url_req_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(consume_url_req, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(consume_url_req, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(consume_url_req));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_consume_5furl_5freq_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    consume_url_req_descriptor_, &consume_url_req::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_consume_5furl_5freq_2eproto() {
  delete consume_url_req::default_instance_;
  delete consume_url_req_reflection_;
}

void protobuf_AddDesc_consume_5furl_5freq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025consume_url_req.proto\022\006spider\"\037\n\017consu"
    "me_url_req\022\014\n\004urls\030\001 \003(\t", 64);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "consume_url_req.proto", &protobuf_RegisterTypes);
  consume_url_req::default_instance_ = new consume_url_req();
  consume_url_req::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_consume_5furl_5freq_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_consume_5furl_5freq_2eproto {
  StaticDescriptorInitializer_consume_5furl_5freq_2eproto() {
    protobuf_AddDesc_consume_5furl_5freq_2eproto();
  }
} static_descriptor_initializer_consume_5furl_5freq_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int consume_url_req::kUrlsFieldNumber;
#endif  // !_MSC_VER

consume_url_req::consume_url_req()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void consume_url_req::InitAsDefaultInstance() {
}

consume_url_req::consume_url_req(const consume_url_req& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void consume_url_req::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

consume_url_req::~consume_url_req() {
  SharedDtor();
}

void consume_url_req::SharedDtor() {
  if (this != default_instance_) {
  }
}

void consume_url_req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* consume_url_req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return consume_url_req_descriptor_;
}

const consume_url_req& consume_url_req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_consume_5furl_5freq_2eproto();
  return *default_instance_;
}

consume_url_req* consume_url_req::default_instance_ = NULL;

consume_url_req* consume_url_req::New() const {
  return new consume_url_req;
}

void consume_url_req::Clear() {
  urls_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool consume_url_req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string urls = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_urls:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_urls()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->urls(this->urls_size() - 1).data(),
            this->urls(this->urls_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_urls;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void consume_url_req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string urls = 1;
  for (int i = 0; i < this->urls_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->urls(i).data(), this->urls(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->urls(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* consume_url_req::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated string urls = 1;
  for (int i = 0; i < this->urls_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->urls(i).data(), this->urls(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->urls(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int consume_url_req::ByteSize() const {
  int total_size = 0;

  // repeated string urls = 1;
  total_size += 1 * this->urls_size();
  for (int i = 0; i < this->urls_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->urls(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void consume_url_req::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const consume_url_req* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const consume_url_req*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void consume_url_req::MergeFrom(const consume_url_req& from) {
  GOOGLE_CHECK_NE(&from, this);
  urls_.MergeFrom(from.urls_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void consume_url_req::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void consume_url_req::CopyFrom(const consume_url_req& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool consume_url_req::IsInitialized() const {

  return true;
}

void consume_url_req::Swap(consume_url_req* other) {
  if (other != this) {
    urls_.Swap(&other->urls_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata consume_url_req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = consume_url_req_descriptor_;
  metadata.reflection = consume_url_req_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace spider

// @@protoc_insertion_point(global_scope)
