// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong_req.proto

#ifndef PROTOBUF_pingpong_5freq_2eproto__INCLUDED
#define PROTOBUF_pingpong_5freq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace spider {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pingpong_5freq_2eproto();
void protobuf_AssignDesc_pingpong_5freq_2eproto();
void protobuf_ShutdownFile_pingpong_5freq_2eproto();

class pingpong_req;

// ===================================================================

class pingpong_req : public ::google::protobuf::Message {
 public:
  pingpong_req();
  virtual ~pingpong_req();

  pingpong_req(const pingpong_req& from);

  inline pingpong_req& operator=(const pingpong_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const pingpong_req& default_instance();

  void Swap(pingpong_req* other);

  // implements Message ----------------------------------------------

  pingpong_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const pingpong_req& from);
  void MergeFrom(const pingpong_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 num = 1;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 1;
  inline ::google::protobuf::int32 num() const;
  inline void set_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:spider.pingpong_req)
 private:
  inline void set_has_num();
  inline void clear_has_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_pingpong_5freq_2eproto();
  friend void protobuf_AssignDesc_pingpong_5freq_2eproto();
  friend void protobuf_ShutdownFile_pingpong_5freq_2eproto();

  void InitAsDefaultInstance();
  static pingpong_req* default_instance_;
};
// ===================================================================


// ===================================================================

// pingpong_req

// required int32 num = 1;
inline bool pingpong_req::has_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void pingpong_req::set_has_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void pingpong_req::clear_has_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void pingpong_req::clear_num() {
  num_ = 0;
  clear_has_num();
}
inline ::google::protobuf::int32 pingpong_req::num() const {
  return num_;
}
inline void pingpong_req::set_num(::google::protobuf::int32 value) {
  set_has_num();
  num_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace spider

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pingpong_5freq_2eproto__INCLUDED
