// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: produce_url_req.proto

#ifndef PROTOBUF_produce_5furl_5freq_2eproto__INCLUDED
#define PROTOBUF_produce_5furl_5freq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace spider {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_produce_5furl_5freq_2eproto();
void protobuf_AssignDesc_produce_5furl_5freq_2eproto();
void protobuf_ShutdownFile_produce_5furl_5freq_2eproto();

class produce_url_req;

// ===================================================================

class produce_url_req : public ::google::protobuf::Message {
 public:
  produce_url_req();
  virtual ~produce_url_req();

  produce_url_req(const produce_url_req& from);

  inline produce_url_req& operator=(const produce_url_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const produce_url_req& default_instance();

  void Swap(produce_url_req* other);

  // implements Message ----------------------------------------------

  produce_url_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const produce_url_req& from);
  void MergeFrom(const produce_url_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string urls = 1;
  inline int urls_size() const;
  inline void clear_urls();
  static const int kUrlsFieldNumber = 1;
  inline const ::std::string& urls(int index) const;
  inline ::std::string* mutable_urls(int index);
  inline void set_urls(int index, const ::std::string& value);
  inline void set_urls(int index, const char* value);
  inline void set_urls(int index, const char* value, size_t size);
  inline ::std::string* add_urls();
  inline void add_urls(const ::std::string& value);
  inline void add_urls(const char* value);
  inline void add_urls(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& urls() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_urls();

  // @@protoc_insertion_point(class_scope:spider.produce_url_req)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> urls_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_produce_5furl_5freq_2eproto();
  friend void protobuf_AssignDesc_produce_5furl_5freq_2eproto();
  friend void protobuf_ShutdownFile_produce_5furl_5freq_2eproto();

  void InitAsDefaultInstance();
  static produce_url_req* default_instance_;
};
// ===================================================================


// ===================================================================

// produce_url_req

// repeated string urls = 1;
inline int produce_url_req::urls_size() const {
  return urls_.size();
}
inline void produce_url_req::clear_urls() {
  urls_.Clear();
}
inline const ::std::string& produce_url_req::urls(int index) const {
  return urls_.Get(index);
}
inline ::std::string* produce_url_req::mutable_urls(int index) {
  return urls_.Mutable(index);
}
inline void produce_url_req::set_urls(int index, const ::std::string& value) {
  urls_.Mutable(index)->assign(value);
}
inline void produce_url_req::set_urls(int index, const char* value) {
  urls_.Mutable(index)->assign(value);
}
inline void produce_url_req::set_urls(int index, const char* value, size_t size) {
  urls_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* produce_url_req::add_urls() {
  return urls_.Add();
}
inline void produce_url_req::add_urls(const ::std::string& value) {
  urls_.Add()->assign(value);
}
inline void produce_url_req::add_urls(const char* value) {
  urls_.Add()->assign(value);
}
inline void produce_url_req::add_urls(const char* value, size_t size) {
  urls_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
produce_url_req::urls() const {
  return urls_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
produce_url_req::mutable_urls() {
  return &urls_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace spider

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_produce_5furl_5freq_2eproto__INCLUDED
