// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: produce_url_resp.proto

#ifndef PROTOBUF_produce_5furl_5fresp_2eproto__INCLUDED
#define PROTOBUF_produce_5furl_5fresp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace spider {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_produce_5furl_5fresp_2eproto();
void protobuf_AssignDesc_produce_5furl_5fresp_2eproto();
void protobuf_ShutdownFile_produce_5furl_5fresp_2eproto();

class produce_url_resp;

// ===================================================================

class produce_url_resp : public ::google::protobuf::Message {
 public:
  produce_url_resp();
  virtual ~produce_url_resp();

  produce_url_resp(const produce_url_resp& from);

  inline produce_url_resp& operator=(const produce_url_resp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const produce_url_resp& default_instance();

  void Swap(produce_url_resp* other);

  // implements Message ----------------------------------------------

  inline produce_url_resp* New() const { return New(NULL); }

  produce_url_resp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const produce_url_resp& from);
  void MergeFrom(const produce_url_resp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(produce_url_resp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 res = 1;
  bool has_res() const;
  void clear_res();
  static const int kResFieldNumber = 1;
  ::google::protobuf::int32 res() const;
  void set_res(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:spider.produce_url_resp)
 private:
  inline void set_has_res();
  inline void clear_has_res();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 res_;
  friend void  protobuf_AddDesc_produce_5furl_5fresp_2eproto();
  friend void protobuf_AssignDesc_produce_5furl_5fresp_2eproto();
  friend void protobuf_ShutdownFile_produce_5furl_5fresp_2eproto();

  void InitAsDefaultInstance();
  static produce_url_resp* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// produce_url_resp

// required int32 res = 1;
inline bool produce_url_resp::has_res() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void produce_url_resp::set_has_res() {
  _has_bits_[0] |= 0x00000001u;
}
inline void produce_url_resp::clear_has_res() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void produce_url_resp::clear_res() {
  res_ = 0;
  clear_has_res();
}
inline ::google::protobuf::int32 produce_url_resp::res() const {
  // @@protoc_insertion_point(field_get:spider.produce_url_resp.res)
  return res_;
}
inline void produce_url_resp::set_res(::google::protobuf::int32 value) {
  set_has_res();
  res_ = value;
  // @@protoc_insertion_point(field_set:spider.produce_url_resp.res)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace spider

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_produce_5furl_5fresp_2eproto__INCLUDED
