// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer_register_req.proto

#ifndef PROTOBUF_producer_5fregister_5freq_2eproto__INCLUDED
#define PROTOBUF_producer_5fregister_5freq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace spider {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_producer_5fregister_5freq_2eproto();
void protobuf_AssignDesc_producer_5fregister_5freq_2eproto();
void protobuf_ShutdownFile_producer_5fregister_5freq_2eproto();

class producer_register_req;

// ===================================================================

class producer_register_req : public ::google::protobuf::Message {
 public:
  producer_register_req();
  virtual ~producer_register_req();

  producer_register_req(const producer_register_req& from);

  inline producer_register_req& operator=(const producer_register_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const producer_register_req& default_instance();

  void Swap(producer_register_req* other);

  // implements Message ----------------------------------------------

  producer_register_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const producer_register_req& from);
  void MergeFrom(const producer_register_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:spider.producer_register_req)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_producer_5fregister_5freq_2eproto();
  friend void protobuf_AssignDesc_producer_5fregister_5freq_2eproto();
  friend void protobuf_ShutdownFile_producer_5fregister_5freq_2eproto();

  void InitAsDefaultInstance();
  static producer_register_req* default_instance_;
};
// ===================================================================


// ===================================================================

// producer_register_req

// required int32 id = 1;
inline bool producer_register_req::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void producer_register_req::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void producer_register_req::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void producer_register_req::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 producer_register_req::id() const {
  return id_;
}
inline void producer_register_req::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace spider

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_producer_5fregister_5freq_2eproto__INCLUDED
